# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
# Fabric Properties
# check these on https://modmuss50.me/fabric.html
minecraft_version=1.21.8
yarn_mappings_2001=1.20.1+build.1
yarn_mappings_2002=1.20.2+build.1
yarn_mappings_2003=1.20.3+build.1
yarn_mappings_2004=1.20.4+build.1
yarn_mappings_2005=1.20.5+build.1
yarn_mappings_2101=1.21.1+build.1
yarn_mappings_2104=1.21.4+build.1
yarn_mappings_2105=1.21.5+build.1
yarn_mappings_2108=1.21.8+build.1
yarn_mappings_2109=1.21.9+build.1
loader_version=0.16.14
kotlin_loader_version=1.13.4+kotlin.2.2.0
scala_loader_version=0.3.1.11
# Mod Properties
mod_version=0.1.0
maven_group=org.net.eu.pool.mica
archives_base_name=mica
# Dependencies
# check this on https://modmuss50.me/fabric.html
fabric_version_2001=0.92.6+1.20.1
fabric_version_2005=0.95.1+1.20.5
fabric_version_2101=0.116.5+1.21.1
fabric_version_2104=0.119.4+1.21.4
fabric_version_2105=0.128.2+1.21.5
fabric_version_2108=0.130.0+1.21.8

seed=0