# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
# Fabric Properties
# check these on https://modmuss50.me/fabric.html
minecraft_version=1.21.8
yarn_mappings_2001=
yarn_mappings_2002=
yarn_mappings_2003=
yarn_mappings_2004=
yarn_mappings_2005=
yarn_mappings_2101=
yarn_mappings_2104=
yarn_mappings_2105=
yarn_mappings_2108=
yarn_mappings_2109=
loader_version=0.16.14
kotlin_loader_version=1.13.4+kotlin.2.2.0
scala_loader_version=0.3.1.11
# Mod Properties
mod_version=0.0.3
maven_group=org.net.eu.pool.mica
archives_base_name=mica
# Dependencies
# check this on https://modmuss50.me/fabric.html

cca_version_2001=

seed=0