package org.net.eu.pool.mica

import com.mojang.serialization.{Codec, Lifecycle}
import net.fabricmc.fabric.api.event.registry.FabricRegistryBuilder
import net.minecraft.registry.{MutableRegistry, Registry, RegistryKey, SimpleRegistry}
import net.minecraft.util.Identifier

import scala.annotation.meta.companionObject
import scala.annotation.{MacroAnnotation, compileTimeOnly, experimental}
import scala.collection.mutable
import scala.language.experimental.macros
import scala.quoted.{Expr, Quotes, ToExpr, Type}

/**
 * This macro generates a registry for a class, allowing the [[register @register]] annotation to track its descendants.
 * @param regName The identifier of the registry: registries themselves must be registered in [[net.minecraft.registry.Registries]]
 */
@compileTimeOnly("@hasRegistry is expanded at compile-time")
class hasRegistry(regName: Identifier) extends MacroAnnotation:
  // Macro-class: we receive the `Definition` of what we're applied as well as its companion object (if it has one).
  override def transform(using q: Quotes)(definition: q.reflect.Definition, companion: Option[q.reflect.Definition]): List[q.reflect.Definition] =
    import q.reflect.*
    // First, match on `definition` - we only support generating registries for classes.
    definition match
      // if it *is* a class, extract its name and also save the class itself to `cl`.
      case cl@ClassDef(name, _, _, _, _) =>
        // Next, match on its companion object:
        companion match
          // In our case, we require it to exist and to be a class, since we plan to add givens to it.
          // Save everything for later, since we'll remake it in our return value.
          case Some(cd@ClassDef(cname, constr, parents, self, body)) =>
            // Prepare the list of the statements we want to generate:
            val givens =
              // Typematch (extract the *actual type* of an expression) the class.
              cl.symbol.typeRef.asType match
                // This unconditionally brings the class itself into scope as `t` - we know nothing about it, not even
                //  whether it's an object, but we don't need to know anything to make a registry for it.
                case '[t] =>
                  // Construct `Symbol`s (which are basically fancy variable names, but they also store the type and associated metadata)
                  //  for the registry and its friends. In this case, all the variables are marked as `given` (making them available for
                  //  `summon` to use), as well as synthetic (since they're generated by a macro). The actual names aren't important assuming
                  //  they're unique, so I use a name mirroring the ones Scala generates for unnamed givens. The first `owner` parameter is
                  //  set to the companion object, as they must be - we later append them to the real companion object, so Scala will error
                  //  otherwise. The *final* parameter sets the visibility of the symbol: Scala visibilities are different from Java's four
                  //  visibilities, in that Scala visibilities are based on an *enclosing* type... I'm getting off-topic. Anyway.
                  // Construct three Symbols representing three implicit variables for Registry-related stuff.
                  val keySym = Symbol.newVal(cd.symbol, s"given_RegistryKey_Registry_${name}", TypeRepr.of[RegistryKey[Registry[t]]], Flags.Given | Flags.Synthetic, Symbol.noSymbol)
                  val registrySym = Symbol.newVal(cd.symbol, s"given_MutableRegistry_${name}", TypeRepr.of[MutableRegistry[t]], Flags.Given | Flags.Synthetic, Symbol.noSymbol)
                  val codecSym = Symbol.newVal(cd.symbol, s"given_Codec_${name}", TypeRepr.of[MutableRegistry[t]], Flags.Given | Flags.Synthetic, Symbol.noSymbol)
                  // Generate a list of the actual registry stuff definitions.
                  Seq(
                    ValDef(keySym, Some {
                      // Lift the registry identifier to an expression...
                      val liftedRegName: Expr[Identifier] = Expr(regName)
                      // ...make a RegistryKey from it...
                      val regKey: Expr[RegistryKey[Registry[t]]] = '{RegistryKey.ofRegistry[t](${liftedRegName})}
                      // ...and convert it to an untyped Term for our mutilation.
                      regKey.asTerm
                    }),
                    ValDef(registrySym, Some {
                      // Similar to before, but different:
                      // pull out the keySym definition from before, casting it to the type we know it is...
                      val keyExpr: Expr[RegistryKey[Registry[t]]] = Ref(keySym).asExprOf[RegistryKey[Registry[t]]]
                      // ...use Fabric's API to create and register a registry from it...
                      val registryExpr = '{FabricRegistryBuilder.createSimple(${keyExpr}).buildAndRegister()}
                      // ...and nuke type-safety again.
                      registryExpr.asTerm
                    }),
                    ValDef(codecSym, Some {
                      // This is left as an exercise to the reader.
                      '{${Ref(registrySym).asExprOf[MutableRegistry[t]]}.getCodec}.asTerm
                    }),
                  )
            // Return the definition, and a copy of the companion object plus our appended givens.
            List(definition, ClassDef.copy(cd)(cname, constr, parents, self, body ++ givens))
          // Of course, being a macro, we can't simply fail if it doesn't exist! We need to handle this case too.
          // Ideally, we'd handle this case by synthesizing a companion of our own, but I'm too lazy to do that.
          case None =>
            // Get the class's name-if we know what it is. If we do, pass it to report.error, or if not, call it with no position (blaming it on the macro call as a whole).
            cl.symbol.pos.fold(report.error("Missing companion object for @hasRegistry"))(report.error("Missing companion object for @hasRegistry", _))
            // and, since we *must* return, just return the original definition unmodified.
            List(definition)
      // and handle someone applying this to e.g. a function of course, since of course someone will.
      case _ =>
        report.error("Only class definitions may have associated registries")
        List(definition) :++ companion

private var registrarState: Option[mutable.Buffer[Expr[Unit]]] = Some(mutable.Buffer.empty)
@compileTimeOnly("@register is expanded at compile-time")
class register(ident: Identifier) extends MacroAnnotation:
  override def transform(using q: Quotes)(definition: q.reflect.Definition, companion: Option[q.reflect.Definition]): List[q.reflect.Definition] =
    import q.reflect.*
    // In this case, the annotation will always be applied to an `object` literal.
    // First, we convert `definition` to a `ClassDef` (also making sure it's an object):
    val cl =
      definition match
        case cl@ClassDef(_, _, _, _, _) if cl.symbol.flags.is(Flags.Module) => cl
        case _ =>
          report.error("Only objects may be annotated at this time")
          return List(definition) :++ companion
    // Next, type-match out `t` - this gives us the actual type of the object literal,
    // letting us use it in the registry lookup.
    cl.symbol.typeRef.asType match
      case '[t] =>
        // Now, check if we're still able to add registrations.
        registrarState match
          case Some(l) =>
            // Try to get the registry:
            val registry: Expr[Registry[? >: t]] = Expr.summon[Registry[? >: t]]
              // ...or, in the case a registry doesn't exist...
              .getOrElse:
                // ...show an error to the user,
                report.error(s"No registry found for type ${cl.symbol.typeRef.show}")
                // and use a placeholder expression (???, which would throw an error at runtime).
                '{ ??? }
                // In Scala, '{ and } convert the expression within to an Expr type, which is
                // how macros represent a typed piece of code.
            end registry
            // Next, get an actual value referring to the companion object.
            // I'm not exactly sure how this works, but it does.
            val companion: Expr[t] = Ref(cl.symbol.companionModule).asExprOf[t]
            // Finally, add it all together: add a new statement to our init queue.
            l += '{
              // Normal Registry.register call, plus splices - Expr(x) merely converts the given value to
              // an expression; we need this due to Scala staging restrictions.
              Registry.register(${registry}, ${Expr(ident)}, ${companion})
              // and return nothing, so the types check out
              ()
            }
          case None =>
            // In the case where registrarState is already None, throw an error instead of silently failing.
            report.error("Registrations were processed too early")
    List(definition) :++ companion
end register

// Give the @register annotation a companion object here, so we can make it generally callable.
// Also, add a @compileTimeOnly annotation for safety - it has no reason to exist after macro expansion, so why should it?
@compileTimeOnly("@register is expanded at compile-time")
object register:
  // This is the definition of a 'normal' macro: an inline function that immediately calls a splice.
  // A splice literal, ${...}, takes an Expr expression and splices it into the current execution context
  // If apply() had parameters, we'd forward them to apply_impl here.
  // Note: Due to a Scala restriction, the top-level splice of a macro *must* immediately call a function and do
  //  nothing else. If apply() took parameters (other than the implicit `Quotes` provided by the splice, which is automatically
  //  forwarded to `apply_impl`'s `using q: Quotes`), we'd need to quote them and pass them to apply_impl.
  inline def apply(): Unit = ${ register.apply_impl }

  // And this is the actual implementation of the macro. We take an implicit Quotes parameter (which allows us to inspect
  //  the inside of an Expr, as a Term or its subclasses) and return an expression.
  private def apply_impl(using q: Quotes): Expr[Unit] =
    import q.reflect.*
    registrarState match
      // If registrarState is Some (as it will be unless apply_impl has been called before), extract its terms...
      case Some(terms) =>
        // ...(also changing its value to None, so any more @register or register() calls will error)...
        registrarState = None
        // ...and we create a *block* expression, which will run all of our `terms` and then return the unit `()`.
        Expr.block(terms.toList, '{()})
      // If it's None, which means it's been called before...
      case None =>
        // raise a compilation error at the macro call-site (report.error's second parameter defaults to the macro call)...
        report.error("Registrations have already been processed")
        // and return a dummy Unit expression anyway, since macros should return *something* even when they error.
        '{()}

given ToExpr[Identifier] = new ToExpr[Identifier]:
  override def apply(x: Identifier)(using q: Quotes): Expr[Identifier] =
    '{ Identifier.of(${Expr(x.getNamespace)}, ${Expr(x.getPath)}) }