modid = "hexic"
book = "hexcasting:thehexbook"
default_lang = "en_us"
default_branch = "main"

resource_dirs = [
    "../build2001/resources/main",
    "resources",
    { modid="hexcasting" },
    { modid="minecraft" },
    { modid="hexdoc" },
    { modid="moreiotas" },
    { modid="hexal" },
    { modid="hexcellular" },
]
export_dir = "src/hexdoc_hexic/_export/generated"

[extra.hexcasting]
# NOTE: "!Raw" means "don't apply variable interpolation to this value"
_pattern_regex = { "!Raw"='hexic:(?P<name>.+),(?P<startdir>\w+),(?P<signature>\w+)' }

[[extra.hexcasting.pattern_stubs]]
path = "../build/datagen/patterns.csv"
regex = "{^_pattern_regex}"

[textures]
missing = [
    "hexic:chisel",
    "hexic:engine/gear_delegate",
    "hexic:preferred_mediaweave",
    "minecraft:chest",
]

[template]
icon = "../src/main/resources/assets/hexic/icon.png"
include = ["hexic", "hexcasting", "hexdoc"]

[template.args]
mod_name = "Hexic"
author = "pool"
show_landing_text = false

[[template.args.navbar.center]]
text = "Modrinth"
href = "https://modrinth.com/mod/hexic"
[[template.args.navbar.center]]
text = "Codeberg"
href = "https://pool.net.eu.org/git/hex-addons"
[[template.args.navbar.center]]
text = "Radicle"
href = "https://radicle.network/nodes/seed.lama2923.dev/rad:zChmxddnxPemALy4RuZ7zQgzDxYv"
[[template.args.navbar.center]]
text = "Tangled"
href = "https://tangled.sh/pool.net.eu.org/hex-addons"

[textures.override]
"hexic:preferred_mediaweave" = { texture = "hexic:textures/item/magenta_mediaweave.png" }
