org.gradle.jvmargs=-Xmx3G
loom.mixin.useLegacyMixinAp=false
loom.platform=neoforge

minecraft_version=1.21.1
yarn_mappings=1.21.1+build.3
neo_forge_version=21.1.111
architectury_version=13.0.8

mod_version=0.1.3-neoforge-probe
maven_group=org.eu.net.pool
archives_base_name=phlib

hexcasting_version=0.12.0-devel-pre-39
inline_version=1.2.2
cloth_config_version=15.0.130
patchouli_version=1.21.1-92-NEOFORGE
paucal_version=0.7.1-pre-27
caelus_version=7.0.1+1.21.1
mixinextras_version=0.5.0
serialization_hooks_version=0.4.99999
forge_kotlin_version=5.11.0
scala_runtime_merged_version=2.13.15-3.7.1
