pluginManagement {
    repositories {
        gradlePluginPortal()
        mavenCentral()
        maven { url "https://maven.architectury.dev/" }
        maven { url "https://maven.fabricmc.net/" }
        maven { url "https://maven.neoforged.net/releases/" }
    }
}

dependencyResolutionManagement {
    repositories {
        mavenCentral()
        maven { url "https://maven.architectury.dev/" }
        maven { url "https://maven.fabricmc.net/" }
        maven { url "https://maven.neoforged.net/releases/" }
        maven { url "https://maven.blamejared.com/" }
    }
}

rootProject.name = "iotaworks-neoforge-probe"
